service:
  - docker

script:
- docker build --target test --tag my-test-image .
- docker run my-test-image ./todo_app/test/test_view_model.py
- docker run --env-file .env.test my-test-image ./todo_app/test/test_app.py
- >
    docker run
    -e api_key
    -e token
    -e board_id
    -e todo_list_id
    -e doing_list_id
    -e done_list_id
    my-test-image ./todo_app/test/test_trello_app.py

notifications:
  slack: corndelcapitadevops:1mvKJYYM8Kug88QuER7qiYsp
    on_success: always # default: change
    on_failure: always # default: always

  email:
    recipients:
      - shiva.hanchate@capita.com
    on_success: always # default: change
    on_failure: always # default: always