service:
  - docker

env:
  global:
  - secure: "p0VzwfInI3U0O7+5Sy7kDRjS1F9B/w1avmzRpuIdHwSSZBMc18RsFwhlBqNed/gliw99QEdlyHkieh4KkTdyh+2H87ngrZFMIG2WBHhcq/EcJIv3jX1/AKDKyMo2t+F/SRtrs0nhWmntGw3zO4xFAk1S2ZW3Iotq2eyaYDSCE6fBurgZSWtd+YIl9qBnU7the5w1VWhl0MSr4E3+nGUG/DtgDa6TOKgJICXqkNPUWAIKNK/epZMhxxqcRWIFEUCMXHdJ1XV4hIByE5adEGkXCrqFIllbrbr8VM7tJfXvdH2TpQlrnKXoX/QfHfqkgrq8/pP/FOkapUNdCCHvbV3VCnQ9d13riMy0l6MXTL+BLreiKwItYRjkwrQva/OWSvBMz4T1J+r9Wby7gi6x8BvVuymhqT4N3BFey6sNmEyHyZbzhupCt6Zt+aLsD8+DCWLABa1v4J00btXQ21s/rFGLQLGsGpfb10fgXHMzDWbus83o5MhXWQLFWKaW3UuRbbG9b+m2zom/Pxgwo+fOL6r0e8bR3HPh8fkmwwOftd5L7ee0csK9d7wiYVOmG2uiF22Mq2LVAeTHRWfrhoTB3BPEJ2E0MniVDht6I9Sa5UnIiyBdOZ+vJ7OpccWMYVI0GabZIBGMVz4bzfMZFJYlrojuxybQ5gB9vgihPrHKw07weKE="
  - secure: "iwA25aSfU9uRNhmmMFUajaAUqzDmtN56eLX1bq5k5MTGoBAv2I0R1zUENpN8dCCWGMUInJRyn2PXHRdDA2lKlxl0W0osJBY8Hrcjm5OjQ4YTFE9wdwxORfJKHD9P0AfB5tU104N8AJrr3taq9A22O/pGbCjXPl+79/pGiqS9kPA0YZh/Vua+/tfGSjdOWoy5hQJtRJThN77dUJoJpWR3iVL6AJn6IElAzu2EzSRJz/9rJHTmsfq34alLVNysdVDY5NkMCDkZTTAxzrNTwePXKnbHeFELoHbnaB9vznCT4kzJ9yScTGXlzmy9b2bRJ/5756ZxN4EJ/Ltyl4qxHR8kAY9kOFZgG4MY6aTsWYHW6vRxJ8ZlIHCzEYVgP9mx2cZi+Go8ZcyQN1OkCpTR+1y9Lwwns454tS0A5fx/boyECBSpej9M+JF6yRrLdwE8BGhtANvU9c+N/ZDQofuAI332uAZVp8/rDSQ8c8IpU1banu0R6QmuWvKxPdpOvaaHcZCnzXkI4e5eY7cM0P0LmLGJwzX01ndL3nXUmGo+kW9GVghIVCgJXJ1+wHuge9iVCrCfqJkrtCrAPOwz9FL8h5UTJq2fTc+LQmiCAWXYJd3Fuu3lPN1z6ZB9nemNGa61IAYksF/VThqp/ZUzXR6rruggDd8Tk/36u81YCDeiEysDp/Q="
  - secure: "IRtsc3+yyuPC1T95DDHRI1IefwtAv6HFFn0zNhH+27MCz3cAzYcUzxQZd0ME3qq4lIbdH5Lk9w73lmTRJEUIXc/0i7uObP2aVCUPhzN2U/NzjbdP4cNdBKi2s1GmWSQE9pgecmFdLhYhOf4/6b8GMURIpLRio/2PLsZQrIYmGIPsS57AY1NB5+h3sZqekFMNJyO3TnSsgavCIpdnq38CByHBrjN1jcMzrH9TCsoPeHZe1AxoMrJOpBNHMXMRCMF+Iyzj7giy04Xzbf+6Fs/JQfkGKPd2zyA7JuClCxHNIyI/QJGltJH0Es9xoBT5PiB/utmSbUB8sqUZSR6O/P9PTlJS4CZtjUWzKpIL7dEBQnNxYmNQ+e32vrmimx0mJsJ1q2F2vlcY3oa1/tA6DCdTWT9u9OdGBUWnlBqwJzGMMyO1tKCqWPGKFrVFEzkznREabZ93ipva4VDkdqLdwmhm1sQS2TyJADDE+9bqfyjox73WZGIRhIMX6t+8uLc4xHav0fsy5EeF/A6URkbJK8Z7tI36QN5ZUbX4QRIzRUlfYwqPY1oM/fCLXp7ebWRTYQN9d61rHiRPZq37R4idZG8RMJI+rMuMqHiJB87LRobQyuwH7gUiqetJ3BSgm6lE0rkb+e9BzdnUc8SWXTsRwbnvTcbkSajPp4zmAWxjd/7n80E="
  - secure: "KbAMQLtJjOM5wnJm5eyCdUS/efJs5RqFCRmDR/g90Hs2JM73i4NRR9xSdrvGn6TWkVlGpZcVfD1VuyiyqKiGEmysK/rF72HaeWt8Bje491PCev8gkURtREHN6JfH/1FfSK8MViHSSYG8utDJttm6EdTXGK9VUT7rUXUt78WBI5rmpX672QFHk2xLdaH3odPQ905koY8bxl5PMJgKAiwEirIgUb8SM046smQUdXOGV/NUb0EPv9d1k5x2aF+MMrpWfnTpGv0On/cSsohToyTQMcrWV2HMpTAfPRLe4ogW+F/V9glPnP62Nk53/AQh2ckc77TEJHMUrRoaQfyKTfc8usl6GyI/1klNcleW7tbt+GUeWyREAjQEzKQttuDj3Qo0MWns7eSiOAvGqSlderi0QNDFp925z3meuKOel3/VDVsIP/kd0pQtNMswXqK7VsOVoCfdrCJPMJrekVnQVEQJaas35MrVjhh/YxicrRVv1bH/8jBBrm1VsOCev6nq3VmnARzvajGdF74qdDCdzem9Q4xOH4EMtj4Syk4bHgtx+Dzh+9Iy3EUGg+kiSOIS9WAvrjSt/zN9QEYq9u0cFXxAbxRFQtMqj9qJgjb31+vwTGJuCrl7gp1cxHf11BDIjJEhu+k/IoLFu6CazVW1bvRAdEpkrNU46SB0zMGZmNuDj1Y="

script:
- docker build --target test --tag my-test-image .
- docker run my-test-image ./todo_app/test/test_view_model.py
- docker run my-test-image ./todo_app/test/test_app.py
- >
    docker run
    -e api_key
    -e token
    my-test-image ./todo_app/test/test_trello_app.py

notifications:
  slack: 
  -e slack
    on_success: always # default: change
    on_failure: always # default: always
  email:
    recipients:
    -e emailaddress
    on_success: always # default: change
    on_failure: always # default: always
