service:
  - docker

env:
  global:
  - secure: "p0VzwfInI3U0O7+5Sy7kDRjS1F9B/w1avmzRpuIdHwSSZBMc18RsFwhlBqNed/gliw99QEdlyHkieh4KkTdyh+2H87ngrZFMIG2WBHhcq/EcJIv3jX1/AKDKyMo2t+F/SRtrs0nhWmntGw3zO4xFAk1S2ZW3Iotq2eyaYDSCE6fBurgZSWtd+YIl9qBnU7the5w1VWhl0MSr4E3+nGUG/DtgDa6TOKgJICXqkNPUWAIKNK/epZMhxxqcRWIFEUCMXHdJ1XV4hIByE5adEGkXCrqFIllbrbr8VM7tJfXvdH2TpQlrnKXoX/QfHfqkgrq8/pP/FOkapUNdCCHvbV3VCnQ9d13riMy0l6MXTL+BLreiKwItYRjkwrQva/OWSvBMz4T1J+r9Wby7gi6x8BvVuymhqT4N3BFey6sNmEyHyZbzhupCt6Zt+aLsD8+DCWLABa1v4J00btXQ21s/rFGLQLGsGpfb10fgXHMzDWbus83o5MhXWQLFWKaW3UuRbbG9b+m2zom/Pxgwo+fOL6r0e8bR3HPh8fkmwwOftd5L7ee0csK9d7wiYVOmG2uiF22Mq2LVAeTHRWfrhoTB3BPEJ2E0MniVDht6I9Sa5UnIiyBdOZ+vJ7OpccWMYVI0GabZIBGMVz4bzfMZFJYlrojuxybQ5gB9vgihPrHKw07weKE="
  - secure: "iwA25aSfU9uRNhmmMFUajaAUqzDmtN56eLX1bq5k5MTGoBAv2I0R1zUENpN8dCCWGMUInJRyn2PXHRdDA2lKlxl0W0osJBY8Hrcjm5OjQ4YTFE9wdwxORfJKHD9P0AfB5tU104N8AJrr3taq9A22O/pGbCjXPl+79/pGiqS9kPA0YZh/Vua+/tfGSjdOWoy5hQJtRJThN77dUJoJpWR3iVL6AJn6IElAzu2EzSRJz/9rJHTmsfq34alLVNysdVDY5NkMCDkZTTAxzrNTwePXKnbHeFELoHbnaB9vznCT4kzJ9yScTGXlzmy9b2bRJ/5756ZxN4EJ/Ltyl4qxHR8kAY9kOFZgG4MY6aTsWYHW6vRxJ8ZlIHCzEYVgP9mx2cZi+Go8ZcyQN1OkCpTR+1y9Lwwns454tS0A5fx/boyECBSpej9M+JF6yRrLdwE8BGhtANvU9c+N/ZDQofuAI332uAZVp8/rDSQ8c8IpU1banu0R6QmuWvKxPdpOvaaHcZCnzXkI4e5eY7cM0P0LmLGJwzX01ndL3nXUmGo+kW9GVghIVCgJXJ1+wHuge9iVCrCfqJkrtCrAPOwz9FL8h5UTJq2fTc+LQmiCAWXYJd3Fuu3lPN1z6ZB9nemNGa61IAYksF/VThqp/ZUzXR6rruggDd8Tk/36u81YCDeiEysDp/Q="
  - secure: "eMOpQa72fR66ZAsb9UrVfMOX6DaXnNolzr0/UzTX8X4xjEz2apixicoIzxLs9YfZgQ20gQ9n7bsxBZm80duZMoKVduEvWP0A6jVfyZdoWKMlcfxIBt0LjxY1yQMnoNm2L+JdBHE4JySp/K/+yd162i+eYTCKFVPIKB58Oy9mbm+htnYpJA4J3iAc040k5jWibwweNOOP3HvdyXhrSv/DOvav7KG3JQaWS9ssj+mQG4/SNEigoAmeLR2ZhBqedmErayzblC2y5K5Qx38+xDzulaeLvrHqdDhLVtgRqJnVUadKHxttFUCTIlQ8JxoEecx+FCR/iROy70g5Lax9J1Upd6CgVG3xq1729T0inQnJGRpWHcH2GWZZ1ifWnNEVn8KzVdX4CLjUaUiXFgZdFZHJ0hYhSP1VdgEdUmfqQhxOgR4Jb1Z4RgL1jtT8c4AaRDfpgiNyYDm/+SiCfFFVMybGGJfq1zP6Y+/SWvl0XVkbT/o9E2Z2hzIMkOVuY3yBOgRtWpnG3obaXNMVc6lxvhaBSDybDsBzcohuQMTiTnXCcZFK1RvIuAy9Aoxq9h/o1gg3jLSo8bnjo8dzW4GrbXZmS7jzglt6gk/mUOWERaxFIXTPjFEVkWshr5kzci5ZczEIPtetQrZm3g4gjhl/++M4Xxu8SMOkGssUdWt2wwIKag8="
  - secure: "eBSY0SkpmYnWHKdcm5TJccawa0WolZ3nV0XwzUv4bOkEBDvlBJxLdTjY6nlAyw3zngn5c66/hv2Pk1jyn3YoE17RfunQgZ3C+RrU0QZqlOhX2mbZtEwuFl3qE83l6ztdEubm/bh9aaVHIWouS8kWs93l3ycxu3bikuMzBRRrCCbeIiDkseiOY9n+XMPpTKrGXOoo5pPRNLBZ9lhf9aSlzPTG3AqCDa7SBn85GIV9IPuYuiFq2nZ6IavAs/Sk2nRd0QRb0S8Y3OZbI6s9jaG5Du28HRhAcQYQ3bIZWPrjOZFgqsWw7yPiDRQdarO4Cj/0KaRi6CJEtHMPHWl5WU13Ee7xLoCUWsHn1xf5cjdj277FDjDmw8W1ObiF8YM+TSYWd4Yw8hg/VPMC2pFpapN6i71C06YCX9Rda02zbOGZJtEZBekke40ULbVEn3ywXNIATkmcD7qDqgtLlz+DZ7kusJYt700Ng7Gnzh5g3Mt8MsBW2hD6dH/EHSnPyRuRE9uLvf3tt4a4dJsPD3RklPWi8JB6NRT97kjroI7P/v0ju0aB1e7TYQ9iop+OAFhanN5qdRn05+rRHxRAqPtoONhFD+OWPgL8FFP3hQun/cbh8I9d+6xWU1AlhUAgYslE+EEOCtjyF+g57LwKy/7MnYa1qYLfl7V5DO0iIDet4z6uaOI="
  
script:
- docker build --target test --tag my-test-image .
- docker run my-test-image ./todo_app/test/test_view_model.py
- docker run my-test-image ./todo_app/test/test_app.py
- >
    docker run
    -e api_key
    -e token
    my-test-image ./todo_app/test/test_trello_app.py

notifications:
  -e slack

  email:
    -e recipients
    on_success: always # default: change
    on_failure: always # default: always
