service:
  - docker

env:
  global:
   - secure: "Qbb8tOj9Qc1nkHqxQ5yheZGC25QSQ71SPCvvdVRFd06nE8s7uythABCzAfzIwDe8hAzW/DGOTNvHuL5Qgl3zWB0mKacjm11dY4c6OcaLB7O1Kn91YsGNoUaXqjain/lzWKqWTO7lCdbVk4pZ6BNKaUx9NI1G+vBDH+F70ayrc5mq/UIAfqC7u8aEUEvTSM642n2hovZJnYDVkLGLHjtJNMhPTYWf5vq+fzbcQrlRYbWc0AnhtHO3ScI99V1kf4NSBkTMB4Z7j6hj3vKhfLbsrlynbkNIyHjz4WrSAy0yT/YRShwxRD/WWx7IyciIrYkIW8VmXQQ3dcSuz1toE3wU0ekxgnuYDUcuKZxn307rlz4TbOC/cJoNhZV6TiHxXPlv+aTutr/sQpP09a7CFa4syKlm/143rvG9fux/m5CagpVKcXnP2xyKOnOy0pbjOx4p9R/87kTazxwNVti6pB53DkauHlBy5GSu++QQ1t3zgmlN/wb/l1qumYuwg+gz8XX1VbaZDlYJ9xn5hxwgrjsEkJUm5KUg433kSnawMoiwJqHgpEW5/LmdUb9KCaadbJWRZbbNc+wXCE3xXYPqEowFUocjMUz/2DLBYyQ4hlsQQdiQrHGksQeIWzLP3Oj4Ru61Ky1mkZl/vAf1RsXTIe7nerCJPzM4sOjqqrlQGTkkfRs="
  
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # command to login to docker hub 
  - curl https://cli-assets.heroku.com/install.sh | sh
  - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
 
script:
- docker build --target test --tag my-test-image .
- docker run my-test-image ./todo_app/test/test_view_model.py
- docker run my-test-image ./todo_app/test/test_integration.py
- >
    docker run
    -e user_name=$MONGODB_USER_NAME
    -e password=$MONGODB_PASSWORD
    -e mongo_url=$MONGO_URL
    -e database_name=$DATABASE_NAME
    -e collection_name=$COLLECTION_NAME    
    my-test-image ./todo_app/test/test_e2e.py

before_deploy:
  - docker build --target production --tag $DOCKER_USERNAME/todo-app:$TRAVIS_COMMIT .
  - docker tag $DOCKER_USERNAME/todo-app:$TRAVIS_COMMIT registry.heroku.com/$HEROKU_APP/web
  - docker push $DOCKER_USERNAME/todo-app:$TRAVIS_COMMIT
  - docker push registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script: heroku container:release web --app $HEROKU_APP
  on:
    branch: Module-9
    
notifications:
  slack: 
    rooms:
      - secure: "f5jE+lxsALMs7M89FFdh/s+QcSw4yQchFfOiBLDd4gOxi3kXta4fGV7ypPBneuXfpxyQvpVIiI3xv8JcahEAr/TiC+M42iDlYnm6DqZYioPfds8TwfuyCJDg15SOiz/khJ+pmsztr8xVL0Gs6NIKL86GBi6ZryqywHJByydNKzMQRrL+jjNGFOBcGouieUXNW1AIOflBjeiMk910IrpFE7qfWMXX/1c5Mq/51J5t6OeCjIO256DBt8/Kk4xvUIgvIgv3TuIg61NLlIE6vQmNRKuJzOyV1HrYK6P+ISAFUvpmGmD+jXnOfQBw0cKOpncnBfpsQWJVIzyuVndgNMZKmTQdCNy/vBXwJsz4VKszZKfPJBiT/Xr0nH/zL81JS+h/Ib+nI4G4NJ4PIoUcKXy+TVn87N6jrdLQrphuCf1M8FoblqrjuIIe0RUyijrXZrrSdE+swnCxv1+sSKgysOqTy9AvM7sPl2M86uEqKTxqwa0kRfWIvMXWpPDpTKiQWpWpD8jNgM0KzE+Uc1sQG/tV2LPtbPIB3AoWyHburXx4cZb34z2n9W+5hhFWAy75FRTT1ld0LheuP/Nv596FZm0imMcKafRVP+5T65gpbXcGB2GRAWc+OSwpgtDbrcaFz9RF3ImCJKv5f5Ve+QKluLszQevKsll2rWCsoeHuQFxov8U="
    on_success: always # default: change
    on_failure: always # default: always
  email:
    recipients:
      - secure: "f9qKfSUGq+KM+E49TVf9YqutdGpYLRKP8KXHF945Q+sXEDPlNS2lu8omBW4mwVt07/dNgoqwVUNLK5kyop1E637tjJg/A3FqTEkgpxJ/5SxCJB8EFQlPEOdNGk4yqMjvkuB50WDw+yS9iloXMRXWHAiOVr2EDH2wqUdSFr2N0UYTJxemk2OG/lQzJe0/vKyzlWULVgFkgYjcBm4xEIXK5WXs6CfpAYrZi5SgrWZgQlIBnCwIRzYgE0bl0vvToPJkhzwGBe1aiBDVVN3LR5rlmDKiQ6L/zhDt8G4OKK0BT/nsZka9FU0AaWGuNf2HFfAtypdgPNUuxwjTbFZhAu9WXR+GRUuuZKzN0OBA5oPfPSdC7amsEs23K3oYRogxwY6+mjW3qzdWGCioGNdl8zY4kF+OO0ktP31ReuPjCumvambGUPKn91u0+OV05KT7JLB26BhByyQi/8giAjI/BWEoK2nLuEf69XZ1blbCRHozRHrpf+FHfmMoAGf/TnhEY90JZ9ID5vpPBrhPQJiI81TBiJjMEOAmdxlS1xRW3lgw7gy4HxQqTuzD8/FDBXThsK0MFKFNNN2gOe8orEQMAskfskA8sWv0cjuF6CH0tWOevS0qZSuMZ1zx9hItdjraSHlCo5tLOeghi2yABRDHPacpWlNvFeHcgLqSvJuN9X3Nq2s="
    on_success: never # default: change
    on_failure: always # default: always
