service:
  - docker

script:
- docker build --target test --tag my-test-image .
- docker run my-test-image ./todo_app/test/test_view_model.py
- docker run my-test-image ./todo_app/test/test_app.py
- >
    docker run
    -e api_key
    -e token    
    my-test-image ./todo_app/test/test_trello_app.py

notifications:
  slack: 

  email:
    recipients:
      - shiva.hanchate@capita.com
    on_success: never # default: change
    on_failure: always # default: always
